# Generated by Django 4.1.2 on 2022-10-15 09:52

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='artist',
            managers=[
                ('albumset', django.db.models.manager.Manager()),
            ],
        ),
    ]
