# Generated by Django 4.1.2 on 2022-10-14 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 14, 22, 54, 8, 31315, tzinfo=datetime.timezone.utc)),
        ),
    ]
