# Generated by Django 4.1.2 on 2022-10-15 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 15, 9, 15, 55, 264375, tzinfo=datetime.timezone.utc)),
        ),
    ]
