# Generated by Django 4.1.2 on 2022-10-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_alter_album_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='creation_date',
        ),
    ]
