# Generated by Django 4.1.2 on 2022-10-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_alter_album_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation_date',
            field=models.DateTimeField(default='2022-10-15T09:27:25.421025+00:00'),
        ),
    ]
