# Generated by Django 4.1.2 on 2022-10-15 09:47

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0012_alter_album_artist_alter_album_creation_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='album',
            managers=[
                ('albumset', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 15, 9, 47, 36, 144187, tzinfo=datetime.timezone.utc)),
        ),
    ]
